import mysql.connector as c
con=c.connect(host="localhost",user="root",password="root",database="lib")
cur=con.cursor()
from tkinter import *
def stud_dis():
    disp=''
    cur.execute("select * from student;")
    disp=cur.fetchall()
    def back1():
        root.destroy()
    root=Tk()
    root.geometry("300x300")
    root.title("libary program")
    x=LabelFrame(root, text="Display")
    x.pack(fill="both", expand="yes")
    txt=Label(x, text=disp)
    txt.pack(anchor=CENTER)
    btn=Button(x,height=3,width=7,text="back",command=back1)
    btn.pack(anchor=S)
    root.mainloop()
def ad1():
    bo=False
    def back():
        root.destroy()
    def ad():
        i=int(a.get())
        n=b.get()
        cl=c.get()
        cur.execute(f"insert into student values({i},'{n}','{cl}');")
        con.commit()
        root.destroy()
    root=Tk()
    root.title("libary program")
    root.geometry("200x200")
    y=LabelFrame(root, text="enter details")
    y.pack(fill="both", expand="yes")
    txt=Label(y, text="student id")
    txt.pack()
    a=Entry(y, width=10)
    a.pack()
    txt1=Label(y, text="student name")
    txt1.pack()
    b=Entry(y, width=10)
    b.pack()
    txt2=Label(y, text="class")
    txt2.pack()
    c=Entry(y, width=10)
    c.pack()
    d=Button(y, text="done",height=1,width=3,command=ad)
    d.pack()
    e=Button(y, text="back",height=1,width=3,command=back)
    e.pack()
    root.mainloop()
def sdel():
    def back():
        root.destroy()
    def clk():
        idel=int(y.get())
        cur.execute("delete from student where sid={};".format(idel))
        con.commit()
        root.destroy()
    root=Tk()
    root.title("libary program")
    root.geometry("200x200")
    x=LabelFrame(root,text="Enter Id To Be Deleted")
    x.pack(fill="both", expand="yes")
    y=Entry(x, width=10)
    y.pack()
    d=Button(x, text="done",height=1,width=3,command=clk)
    d.pack()
    e=Button(x, text="back",height=1,width=3,command=back)
    e.pack()
    root.mainloop()
 
def ssea():
    def clk1():
        idel=int(y.get())
        cur.execute("select * from student where sid={};".format(idel))
        disp=cur.fetchall()
        root.destroy()
        root1=Tk()
        root1.geometry("300x300")
        root1.title("libary program")
        x=LabelFrame(root1, text="Display")
        x.pack(fill="both", expand="yes")
        txt=Label(x, text=disp)
        txt.pack(anchor=CENTER)
        btn=Button(x,height=3,width=7,text="back",command=root1.destroy)
        btn.pack(anchor=S)
        root1.mainloop()
    root=Tk()
    root.title("libary program")
    root.geometry("200x200")
    x=LabelFrame(root,text="Enter Id To Be Searched")
    x.pack(fill="both", expand="yes")
    y=Entry(x, width=10)
    y.pack()
    d=Button(x, text="done",height=1,width=3,command=clk1)
    d.pack()
    e=Button(x, text="back",height=1,width=3,command=root.destroy)
    e.pack()
    root.mainloop()
